import{i as a}from"./assets/vendor-ad859c2f.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function c(s){const o="https://pixabay.com/api/",t=new URLSearchParams({key:"43011845-ca4f94d8d544ea7c100ad449b",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),n=`${o}?${t}`;return fetch(n).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const l=document.querySelector(".gallery");function m(s){if(s.length===0)iziToast.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const o=s.map(t=>`<li class="photos-list-item">
  <a class="photos-list-link" href="${t.largeImageURL}">
  <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
  </a>
  <ul class="photo-information-container">
  <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
  <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
  </ul>
  </li>`).join("");l.insertAdjacentHTML("beforeend",o)}}const u=document.querySelector(".search-form");document.querySelector(".gallery");u.addEventListener("submit",p);function p(s){s.preventDefault();const o=s.target.elements.search.value.trim();o!==""?c(o).then(t=>{m(t.hits)}):a.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
